<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251125165742 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE short_urls (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_url VARCHAR(2048) NOT NULL, short_code VARCHAR(20) NOT NULL, clicks INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4A53F93481B35420 ON short_urls (original_url)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4A53F93417D2FE0D ON short_urls (short_code)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE short_urls');
    }
}
